server {
    listen 80;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;
    index index.html index.htm;

     error_page 403 =404 /error;

    location /gov {
        alias /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ @router;  
         autoindex off;  # 關閉目錄索引
    }
   
   location @router {
          if ($request_uri ~* "%20|%7e|\.bak|\.old|\.zip|\.tar") {
            return 404;
        }
 
        rewrite ^.*$ /index.html last;
    }
 
    # 禁止 dotfiles
    location ~ /\. {
        deny all;
        return 404;
    }
}