export enum PageItem {
    // primeVue component
    AutoComplete,
    CascadeSelect,
    Checkbox,
    CheckboxGroup,
    ColorPicker,
    DatePicker,
    Editor,
    FloatLabel,
    IconField,
    InputGroup,
    InputMask,
    InputNumber,
    InputOtp,
    InputText,
    InputTextRegular,
    Knob,
    Listbox,
    MultiSelect,
    MultiSelectSearch,
    Password,
    RadioButton,
    Rating,
    Select,
    SelectButton,
    Slider,
    Textarea,
    ToggleButton,
    ToggleSwitch,
    TreeSelect,
    Upload,
    MarkDown,
    Button,
    ThemeSwitch,
    ImageView,
    Tag,
    ProgressBar,
    CheckboxPassword,
    VerificationImg,
    Account,
    PasswordRule,
    VerificationCode,
    AI,
    MarkdownEditor,
    PageSection,
    IconButton,
    Divider,
    KeyValue,
    Accordion,
    TabList,
    Txt,
    List,
    SystemLanguage,
    ListSelect,
    CustomMenu
}
export enum PageItemSelectType {
    dropdown,
    combox,
    autocomplete
}


export enum PageItemSeverityStyle {
    NONE = "",
    SECONDARY = "secondary",
    SUCCESS = "success",
    INFO = "info",
    WARN = "warn",
    DANGER = "danger",
    CONTRAST = "contrast",
    ERROR = "error",
    HELP = "help"

}
